### ISSUE TITLE
Need to collaborate on this dataset

### ISSUE THREAD

**Issue by reachshyamal** [geohacker/railways#1]
How can I extract the data from this URL:
http://geohacker.in/railways/zones.html#7.98/22.790/87.668

**Comment by reachshyamal** [comment]
@geohacker are you able to respond to my question above?

**Comment by geohacker** [comment]
Hi! This is all documented in the readme. You can download data from https://github.com/datameet/railways though it is now very old. Let me know what you are looking to do.

**Comment by reachshyamal** [comment]
@geohacker I am looking to optimize schedules of trains in Indian Railways,for that I need 
1.schedules and actual times of individual trains(this can be obtained from "where is my train" mobile application)
2.route network similar to data used in this repo
https://github.com/crowdAI/train-schedule-optimisation-challenge-starter-kit/blob/master/problem_instances/01_dummy.json#L486
For 2.above can similar data be obtained for Indian Railways?

**Comment by geohacker** [comment]
> For 2.above can similar data be obtained for Indian Railways?

I don't there's a very straightforward way unfortunately. I think where's my train may also have the route information you could potentially scrape. For a start you could see what's available the datameet repo.

**Comment by reachshyamal** [comment]
> > For 2.above can similar data be obtained for Indian Railways?
> 
> I don't there's a very straightforward way unfortunately. I think where's my train may also have the route information you could potentially scrape. For a start you could see what's available the datameet repo.

@geohacker in the datameet repo we have schedules of trains but do we have their actual arrival and actual exit times at every possible junction point in the network?
Also , I didn't find scenarios where two trains are looking to occupy same platform/track at the same time,which is there in the Swiss Railways dataset.

**Comment by geohacker** [comment]
@reachshyamal I think you'd have to look at the datameet data closely to see if that's useful for your work. I unfortunately don't have time to go over that right now. Good luck!
